### ISSUE TITLE
Issue during build using ROS2 Iron

### ISSUE THREAD

**Issue by Rubidion** [arshadlab/gazebo_map_creator#1]
I really appreciate your effort in building this very useful tool for gazebo. However, I cannot currently get it to build on ROS 2 Iron due to some issue with how the boost libraries and ROS seem to be interacting. My error output is attached below. Did you have this issue? and if so, what did you do to solve it?

If not, what version of ROS 2 are you using so I might be able to see where the issue lies. Thank you.

[stderr.log](https://github.com/arshadlab/gazebo_map_creator/files/12032870/stderr.log)

**Comment by arshadlab** [comment]
Thank you.    I tried on Foxy & Humble and now it should work on Iron too.  Fix the header placement issue.

**Comment by arshadlab** [comment]
Is the issue resolved ? can I close this ticket ?

**Comment by Rubidion** [comment]
Oh my apologies I meant to reply. Yes it worked wonderfully, thank you!

**Comment by arshadlab** [comment]
Good to hear that. I will proceed with closure of this issue.
